routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::post('/login/custom', [
    'uses' => 'LoginController@login',
    'as' => 'login.custom'
]);


//Resource
Auth::routes();


//user
Route::group(['middleware' => ['auth' => 'user']], function () {
    Route::resource('pengajuan', 'PengajuanController');
    Route::resource('logbook', 'IsiLogbookController');
    Route::resource('magang', 'MagangController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/error_ditolak', 'MagangController@errorPenolakan')->name('error_ditolak');
    Route::get('/error_pengajuan_diproses', 'PengajuanController@errorDiproses')->name('error_pengajuan_diproses');
    Route::get('/error_pengajuan', 'PengajuanController@sudahPengajuan')->name('error_pengajuan');
    Route::get('/error_belum_magang', 'MagangController@error_belum_diterima_magang')->name('error_status');
    Route::get('/error_sudah_diterima', 'MagangController@error_sudah_diterima_magang')->name('error_diterima');
});

//admin
Route::group(['middleware' => ['auth' => 'admin']], function () {
    Route::resource('penilaian', 'PenilaianController');
    Route::get('/home_dashboard', function () {
        return view('admin/home_admin');
    })->name('admin_dashboard');
    Route::get('/list_pengajuan_admin', 'PengajuanController@index_admin')->name('list_pengajuan_admin');
    Route::get('/edit_pengajuan_admin/{id}', 'PengajuanController@edit_pengajuan_admin')->name('edit_pengajuan_admin');
    Route::post('/update_pengajuan_admin/{id}', 'PengajuanController@update_admin')->name('update_pengajuan_admin');
    Route::post('/tolak_pengajuan/{id}', 'PengajuanController@tolak_admin')->name('tolak_pengajuan');
    Route::post('/terima_pengajuan/{id}', 'PengajuanController@terima_ropeg_admin')->name('terima_pengajuan');
    Route::post('/teruskan_kabiro/{id}', 'PengajuanController@teruskan_kabiro')->name('teruskan_kabiro');
    Route::post('/terima_magang/{id}', 'PengajuanController@terima_magang_kabag')->name('terima_magang');
    Route::get('/list_magang_admin', 'MagangController@index_admin')->name('list_magang_admin');
    Route::get('/list_logbook_admin', 'IsiLogbookController@index_admin')->name('list_logbook_admin');
    Route::post('/acc_logbook_admin/{id}', 'IsiLogbookController@acc_logbook')->name('acc_logbook');
    Route::post('/tolak_logbook_admin/{id}', 'IsiLogbookController@tolak_logbook')->name('tolak_logbook');
    Route::resource('tambahadmin', 'TambahAdminController');

    Route::get('/create_penilaian/{id}', 'PenilaianController@create_admin')->name('tambah_penilaian');
    Route::post('/tambah_penilaian/{id}', 'PenilaianController@store_admin')->name('simpan_penilaian');
    Route::post('/selesaikan_magang/{id}', 'MagangController@selesaikan_magang')->name('selesaikan_magang');
});





// guest
Route::get('/alur_pengajuan', function () {
    return view('/user/alur_pengajuan');
})->name('alur_pengajuan');
Route::get('/tentang_simagang', function () {
    return view('/user/tentang_simagang');
})->name('tentang_simagang');

//lain
Route::get('/file/{id}', 'PengajuanController@openFile')->name('open_file');

resources/views/admin/home_admin.blade.php
 @extends('admin.master_admin')
 @extends('admin.komponen.topbar_admin')
 @extends('admin.komponen.sidebar_admin')


 @section('konten_admin')
 <!-- Begin Page Content -->
 <div class="container-fluid">

     <!-- Page Heading -->
     <div class="d-sm-flex align-items-center justify-content-between mb-4">
         <h1 class="h3 mb-0 text-gray-800">Selamat datang admin, {{Auth::user()->name}}!</h1>

     </div>
 </div>
 <!-- /.container-fluid -->

 </div>
 <!-- End of Main Content -->


 @endsection

resources/views/admin/list_magang_admin.blade.php
@extends('admin.master_admin')
@extends('admin.komponen.sidebar_admin')
@extends('admin.komponen.topbar_admin')

@section('konten_admin')

<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Daftar Siswa Magang</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <div class="dataTables_wrapper dt-bootstrap4" id="dataTable_wrapper">
                    <div class="row">
                        <div class="col-sm-12">
                            <table aria-describedby="dataTable_info" cellspacing="0"
                                class="table table-bordered dataTable" id="dataTable" role="grid" style="width: 100%;"
                                width="100%">
                                <thead>
                                    <tr role="row">
                                        <th aria-controls="dataTable"
                                            aria-label="Instansi Pendidikan: activate to sort column descending"
                                            aria-sort="ascending" class="sorting_asc" colspan="1" rowspan="1"
                                            style="width: 64px;" tabindex="0">Instansi Pendidikan</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Mulai Magang: activate to sort column ascending" class="sorting"
                                            colspan="1" rowspan="1" style="width: 56px;" tabindex="0">Mulai Magang
                                            (Tahun-Hari-Bulan)</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Selesai Magang: activate to sort column ascending"
                                            class="sorting" colspan="1" rowspan="1" style="width: 56px;" tabindex="0">
                                            Selesai Magang (Tahun-Hari-Bulan)</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Nama Ketua: activate to sort column ascending" class="sorting"
                                            colspan="1" rowspan="1" style="width: 56px;" tabindex="0">Nama Ketua</th>
                                        <th aria-controls="dataTable"
                                            aria-label="E-Mail Ketua: activate to sort column ascending" class="sorting"
                                            colspan="1" rowspan="1" style="width: 31px;" tabindex="0">
                                            E-Mail Ketua</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Nomor Telpon Ketua: activate to sort column ascending"
                                            class="sorting" colspan="1" rowspan="1" style="width: 68px;" tabindex="0">
                                            Nomor Telpon Ketua</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Nama Anggota 1: activate to sort column ascending"
                                            class="sorting" colspan="1" rowspan="1" style="width: 67px;" tabindex="0">
                                            Nama Anggota 1</th>
                                        <th aria-controls="dataTable"
                                            aria-label="E-Mail Anggota 1: activate to sort column ascending"
                                            class="sorting" colspan="1" rowspan="1" style="width: 67px;" tabindex="0">
                                            E-Mail Anggota 1</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Nomor Telpon Anggota 1: activate to sort column ascending"
                                            class="sorting" colspan="1" rowspan="1" style="width: 67px;" tabindex="0">
                                            Nomor Telpon Anggota 1</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Nama Anggota 2: activate to sort column ascending"
                                            class="sorting" colspan="1" rowspan="1" style="width: 67px;" tabindex="0">
                                            Nama Anggota 2</th>
                                        <th aria-controls="dataTable"
                                            aria-label="E-Mail Anggota 2: activate to sort column ascending"
                                            class="sorting" colspan="1" rowspan="1" style="width: 67px;" tabindex="0">
                                            E-Mail Anggota 2</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Nomor Telpon Anggota 2: activate to sort column ascending"
                                            class="sorting" colspan="1" rowspan="1" style="width: 67px;" tabindex="0">
                                            Nomor Telpon Anggota 2</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Status Magang: activate to sort column ascending"
                                            class="sorting" colspan="1" rowspan="1" style="width: 67px;" tabindex="0">
                                            Status Magang</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Nilai Akhir Kelompok: activate to sort column ascending"
                                            class="sorting" colspan="1" rowspan="1" style="width: 67px;" tabindex="0">
                                            Nilai Akhir Kelompok</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Beri Penilaian: activate to sort column ascending"
                                            class="sorting" colspan="1" rowspan="1" style="width: 67px;" tabindex="0">
                                            Penilaian</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Selesaikan Magang: activate to sort column ascending"
                                            class="sorting" colspan="1" rowspan="1" style="width: 67px;" tabindex="0">
                                            Selesaikan Magang</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th colspan="1" rowspan="1">Instansi Pendidikan</th>
                                        <th colspan="1" rowspan="1">Mulai Magang (Tahun-Hari-Bulan)</th>
                                        <th colspan="1" rowspan="1">Selesai Magang (Tahun-Hari-Bulan)</th>
                                        <th colspan="1" rowspan="1">Nama Ketua</th>
                                        <th colspan="1" rowspan="1">E-Mail Ketua</th>
                                        <th colspan="1" rowspan="1">Nomor Telpon Ketua</th>
                                        <th colspan="1" rowspan="1">Nama Anggota 1</th>
                                        <th colspan="1" rowspan="1">E-Mail Anggota 1</th>
                                        <th colspan="1" rowspan="1">Nomor Telpon Anggota 1</th>
                                        <th colspan="1" rowspan="1">Nama Anggota 2</th>
                                        <th colspan="1" rowspan="1">E-Mail Anggota 2</th>
                                        <th colspan="1" rowspan="1">Nomor Telpon Anggota 2</th>
                                        <th colspan="1" rowspan="1">Status Magang</th>
                                        <th colspan="1" rowspan="1">Nilai Akhir Kelompok</th>
                                        <th colspan="1" rowspan="1">Penilaian</th>
                                        <th colspan="1" rowspan="1">Selesaikan Magang</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @foreach ($magang as $magang)
                                    <tr class="odd" role="row">
                                        <td class="sorting_1">{{$magang->magang_pengajuan->asal_surat}}</td>
                                        <td>{{$magang->magang_pengajuan->mulai_magang}}</td>
                                        <td>{{$magang->magang_pengajuan->selesai_magang}}</td>
                                        <td>{{$magang->magang_pengajuan->nama_pengaju}}</td>
                                        <td>{{$magang->magang_pengajuan->email}}</td>
                                        <td>{{$magang->magang_pengajuan->no_telp}}</td>
                                        <td>{{$magang->magang_pengajuan->nama_anggota1}}</td>
                                        <td>{{$magang->magang_pengajuan->email1}}</td>
                                        <td>{{$magang->magang_pengajuan->no_telp1}}</td>
                                        <td>{{$magang->magang_pengajuan->nama_anggota2}}</td>
                                        <td>{{$magang->magang_pengajuan->email2}}</td>
                                        <td>{{$magang->magang_pengajuan->no_telp2}}</td>
                                        @if($magang->status_magang == 1)
                                        <td>Magang</td>
                                        @else
                                        <td>Selesai Magang</td>
                                        @endif
                                        @if ($magang->magang_nilai['nilai_akhir']>85)
                                        <td>A</td>
                                        @elseif($magang->magang_nilai['nilai_akhir']>=70)
                                        <td>B</td>
                                        @elseif($magang->magang_nilai['nilai_akhir']>=55)
                                        <td>C</td>
                                        @elseif($magang->magang_nilai['nilai_akhir']<=54) <td>D</td>
                                            @endif
                                            @if($magang->magang_nilai['id_magang']==null)
                                            <td>
                                                <a href="{{route('tambah_penilaian', $magang['id'])}}">
                                                <button type="submit" class="btn btn-primary btn-user btn-block">
                                                    Beri Penilaian
                                                </button>
                                            </a>
                                            </td>
                                            @else
                                            <td>
                                                <a href="{{route('penilaian.edit', $magang['id'])}}">
                                                    <button type="submit" class="btn btn-primary btn-user btn-block">
                                                        Ubah Penilaian
                                                    </button>
                                                </a>
                                            </td>
                                            @endif
                                            @if ($magang->status_magang == 1)
                                            @if ($magang->magang_nilai['id_magang'] != null)
                                            <td>
                                                <form action="{{route('selesaikan_magang', $magang['id'])}}" method="post">
                                                    @csrf
                                                    <button type="submit" class="btn btn-primary btn-user btn-block">
                                                        Selesaikan Magang
                                                    </button>
                                                </form>
                                            </td>

                                            @else

                                            <td></td>
                                            @endif
                                            @else
                                            <td></td>
                                            @endif
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


@endsection

resources/views/admin/list_pengguna.blade.php
@extends('admin.master_admin')
@extends('admin.komponen.sidebar_admin')
@extends('admin.komponen.topbar_admin')

@section('konten_admin')

<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Daftar Pengguna</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Daftar Pengguna</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <div class="dataTables_wrapper dt-bootstrap4" id="dataTable_wrapper">
                    <div class="row">
                        <div class="col-sm-12">
                            <table aria-describedby="dataTable_info" cellspacing="0"
                                class="table table-bordered dataTable" id="dataTable" role="grid" style="width: 100%;"
                                width="100%">
                                <thead>
                                    <tr role="row">
                                        <th aria-controls="dataTable"
                                            aria-label="Nama: activate to sort column descending"
                                            aria-sort="ascending" class="sorting_asc" colspan="1" rowspan="1"
                                            style="width: 64px;" tabindex="0">Nama</th>
                                        <th aria-controls="dataTable"
                                            aria-label="E-Mail: activate to sort column ascending"
                                            class="sorting" colspan="1" rowspan="1" style="width: 81px;" tabindex="0">
                                            E-Mail</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Status: activate to sort column ascending"
                                            class="sorting" colspan="1" rowspan="1" style="width: 81px;" tabindex="0">
                                            Status</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Biro: activate to sort column ascending" class="sorting"
                                            colspan="1" rowspan="1" style="width: 31px;" tabindex="0">
                                            Biro</th>
                                            <th aria-controls="dataTable"
                                            aria-label="Biro: activate to sort column ascending" class="sorting"
                                            colspan="1" rowspan="1" style="width: 31px;" tabindex="0">
                                            Bagian</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Ubah Status: activate to sort column ascending" class="sorting"
                                            colspan="1" rowspan="1" style="width: 67px;" tabindex="0">Ubah Status</th>
                                        <th aria-controls="dataTable"
                                            aria-label="Hapus: activate to sort column ascending" class="sorting"
                                            colspan="1" rowspan="1" style="width: 67px;" tabindex="0">Hapus</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th colspan="1" rowspan="1">Nama</th>
                                        <th colspan="1" rowspan="1">E-Mail</th>
                                        <th colspan="1" rowspan="1">Status</th>
                                        <th colspan="1" rowspan="1">Biro</th>
                                        <th colspan="1" rowspan="1">Bagian</th>
                                        <th colspan="1" rowspan="1">Ubah Status</th>
                                        <th colspan="1" rowspan="1">Hapus</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @foreach ($user as $user)
                                    <tr class="odd" role="row">
                                        <td class="sorting_1">{{$user->name}}</td>
                                        <td>{{$user->email}}</td>
                                        @if($user->is_admin==1)
                                        <td>Admin</td>
                                        @else
                                        <td>Pengguna</td>
                                        @endif
                                        @if($user->id_biro==1)
                                        <td>Biro Kepegawaian</td>
                                        @elseif($user->id_biro==2)
                                        <td>Biro Hubungan Masyarakat</td>
                                        @elseif($user->id_biro==3)
                                        <td>Biro Perencanaan</td>
                                        @elseif($user->id_biro==4)
                                        <td>Biro Keuangan</td>
                                        @elseif($user->id_biro==5)
                                        <td>Biro Umum</td>
                                        @else
                                        <td>-</td>
                                        @endif
                                        @if($user->id_bagian==1)
                                        <td>Ropeg 1</td>
                                        @elseif($user->id_bagian==2)
                                        <td>Ropeg 2</td>
                                        @elseif($user->id_bagian==3)
                                        <td>Ropeg 3</td>
                                        @elseif($user->id_bagian==4)
                                        <td>Ropeg 4</td>
                                        @elseif($user->id_bagian==5)
                                        <td>Ropeg 5</td>
                                        @elseif($user->id_bagian==6)
                                        <td>Humas 1</td>
                                        @elseif($user->id_bagian==7)
                                        <td>Humas 2</td>
                                        @elseif($user->id_bagian==8)
                                        <td>Humas 3</td>
                                        @elseif($user->id_bagian==9)
                                        <td>Humas 4</td>
                                        @elseif($user->id_bagian==10)
                                        <td>Humas 5</td>
                                        @elseif($user->id_bagian==11)
                                        <td>Perencanaan 1</td>
                                        @elseif($user->id_bagian==12)
                                        <td>Perencanaan 2</td>
                                        @elseif($user->id_bagian==13)
                                        <td>Perencanaan 3</td>
                                        @elseif($user->id_bagian==14)
                                        <td>Perencanaan 4</td>
                                        @elseif($user->id_bagian==15)
                                        <td>Perencanaan 5</td>
                                        @elseif($user->id_bagian==16)
                                        <td>Keuangan 1</td>
                                        @elseif($user->id_bagian==17)
                                        <td>Keuangan 2</td>
                                        @elseif($user->id_bagian==18)
                                        <td>Keuangan 3</td>
                                        @elseif($user->id_bagian==19)
                                        <td>Keuangan 4</td>
                                        @elseif($user->id_bagian==20)
                                        <td>Keuangan 5</td>
                                        @elseif($user->id_bagian==21)
                                        <td>Umum 1</td>
                                        @elseif($user->id_bagian==22)
                                        <td>Umum 2</td>
                                        @elseif($user->id_bagian==23)
                                        <td>Umum 3</td>
                                        @elseif($user->id_bagian==24)
                                        <td>Umum 4</td>
                                        @elseif($user->id_bagian==25)
                                        <td>Umum 5</td>
                                        @else
                                        <td>-</td>
                                        @endif
                                        <td>
                                            <a href="{{route('tambahadmin.edit', $user['id'])}}">
                                                <button type="submit" class="btn btn-primary btn-user btn-block">
                                                    Ubah
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <form action="#{{--route('pengajuan.destroy', [$pengajuan['id']])--}}"
                                                method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-user btn-block">
                                                    Hapus
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
@endsection

resources/views/admin/ubah_status_pengguna.blade.php
@extends('admin.master_admin')
@extends('admin.komponen.sidebar_admin')
@extends('admin.komponen.topbar_admin')

@section('konten_admin')

<form action="{{route('tambahadmin.update', $status['id'])}}" method="POST">

    <div class="container-fluid">
        @csrf
        @method('PUT')
        <div class="form-group">
            <p>Nama: </p>
            <input type="text" name="nama" class="form-control form-control-user"
                id="nama" placeholder="Nama" value="{{$status->name}}" readonly>
        </div>
        <div class="form-group">
            <p>Status: </p>
        <select name="is_admin" class="form-control form-control-user">
                <option value="Admin">Admin</option>
                <option value="Pengguna">Pengguna</option>
            </select>
        </div>
        <div class="form-group">
            <p>Biro: </p>
            <select name="id_biro" class="form-control form-control-user">
                <option value="-">-</option>
                <option value="Biro Kepegawaian">Biro Kepegawaian</option>
                <option value="Biro Hubungan Masyarakat">Biro Hubungan Masyarakat</option>
                <option value="Biro Perencanaan">Biro Perencanaan</option>
                <option value="Biro Keuangan">Biro Keuangan</option>
                <option value="Biro Umum">Biro Umum</option>

            </select>
        </div>
        <div class="form-group">
            <p>Biro: </p>
            <select name="id_bagian" class="form-control form-control-user">
                <option value="-">-</option>
                <option value="Ropeg 1">Ropeg 1</option>
                <option value="Ropeg 2">Ropeg 2</option>
                <option value="Ropeg 3">Ropeg 3</option>
                <option value="Ropeg 4">Ropeg 4</option>
                <option value="Ropeg 5">Ropeg 5</option>
                <option value="Humas 1">Humas 1</option>
                <option value="Humas 2">Humas 2</option>
                <option value="Humas 3">Humas 3</option>
                <option value="Humas 4">Humas 4</option>
                <option value="Humas 5">Humas 5</option>
                <option value="Perencanaan 1">Perencanaan 1</option>
                <option value="Perencanaan 2">Perencanaan 2</option>
                <option value="Perencanaan 3">Perencanaan 3</option>
                <option value="Perencanaan 4">Perencanaan 4</option>
                <option value="Perencanaan 5">Perencanaan 5</option>
                <option value="Keuangan 1">Keuangan 1</option>
                <option value="Keuangan 2">Keuangan 2</option>
                <option value="Keuangan 3">Keuangan 3</option>
                <option value="Keuangan 4">Keuangan 4</option>
                <option value="Keuangan 5">Keuangan 5</option>
                <option value="Umum 1">Umum 1</option>
                <option value="Umum 2">Umum 2</option>
                <option value="Umum 3">Umum 3</option>
                <option value="Umum 4">Umum 4</option>
                <option value="Umum 5">Umum 5</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary btn-user btn-block">
            Ubah Status
        </button>
    </div>
</form>

@endsection