routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::post('/login/custom', [
    'uses' => 'LoginController@login',
    'as' => 'login.custom'
]);


//Resource
Auth::routes();


//user
Route::group(['middleware' => ['auth' => 'user']], function () {
    Route::resource('pengajuan', 'PengajuanController');
    Route::resource('logbook', 'IsiLogbookController');
    Route::resource('magang', 'MagangController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/error_ditolak', 'MagangController@errorPenolakan')->name('error_ditolak');
    Route::get('/error_pengajuan_diproses', 'PengajuanController@errorDiproses')->name('error_pengajuan_diproses');
    Route::get('/error_pengajuan', 'PengajuanController@sudahPengajuan')->name('error_pengajuan');
    Route::get('/error_belum_magang', 'MagangController@error_belum_diterima_magang')->name('error_status');
    Route::get('/error_sudah_diterima', 'MagangController@error_sudah_diterima_magang')->name('error_diterima');
});

//admin
Route::group(['middleware' => ['auth' => 'admin']], function () {
    Route::resource('penilaian', 'PenilaianController');
    Route::get('/home_dashboard', function () {
        return view('admin/home_admin');
    })->name('admin_dashboard');
    Route::get('/list_pengajuan_admin', 'PengajuanController@index_admin')->name('list_pengajuan_admin');
    Route::get('/edit_pengajuan_admin/{id}', 'PengajuanController@edit_pengajuan_admin')->name('edit_pengajuan_admin');
    Route::post('/update_pengajuan_admin/{id}', 'PengajuanController@update_admin')->name('update_pengajuan_admin');
    Route::post('/tolak_pengajuan/{id}', 'PengajuanController@tolak_admin')->name('tolak_pengajuan');
    Route::post('/terima_pengajuan/{id}', 'PengajuanController@terima_ropeg_admin')->name('terima_pengajuan');
    Route::post('/teruskan_kabiro/{id}', 'PengajuanController@teruskan_kabiro')->name('teruskan_kabiro');
    Route::post('/terima_magang/{id}', 'PengajuanController@terima_magang_kabag')->name('terima_magang');
    Route::get('/list_magang_admin', 'MagangController@index_admin')->name('list_magang_admin');
    Route::get('/list_logbook_admin', 'IsiLogbookController@index_admin')->name('list_logbook_admin');
    Route::post('/acc_logbook_admin/{id}', 'IsiLogbookController@acc_logbook')->name('acc_logbook');
    Route::post('/tolak_logbook_admin/{id}', 'IsiLogbookController@tolak_logbook')->name('tolak_logbook');
    Route::resource('tambahadmin', 'TambahAdminController');

    Route::get('/create_penilaian/{id}', 'PenilaianController@create_admin')->name('tambah_penilaian');
    Route::post('/tambah_penilaian/{id}', 'PenilaianController@store_admin')->name('simpan_penilaian');
    Route::post('/selesaikan_magang/{id}', 'MagangController@selesaikan_magang')->name('selesaikan_magang');
});





// guest
Route::get('/alur_pengajuan', function () {
    return view('/user/alur_pengajuan');
})->name('alur_pengajuan');
Route::get('/tentang_simagang', function () {
    return view('/user/tentang_simagang');
})->name('tentang_simagang');

//lain
Route::get('/file/{id}', 'PengajuanController@openFile')->name('open_file');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_admin', 'id_biro', 'id_bagian',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function pengguna(){
        return $this->hasMany('App\Pengajuan', 'id_pengguna', 'id');
    }

    // public function pengguna_magang(){
    //     return $this->hasOne('App\Magang', 'id_pengguna', 'id');
    // }

    // public function pengguna_logbook()
    // {
    //     return $this->hasMany('App\Logbook', 'id_pengguna', 'id');
    // }

    public function pengguna_biro()
    {
        return $this->belongsTo('App\Biro', 'id_biro', 'id');
    }

    public function pengguna_bagian(){
        return $this->belongsTo('App\Bagian', 'id_bagian', 'id');
    }

    public function is_admin(){
        if($this->is_admin){
            return true;
        }
        else{
            return false;

        }
    }
}

resources/views/user/alur_pengajuan.blade.php
@extends('layouts.app')
@extends('user.komponen.bottombar')
@extends('user.komponen.topbar')

@section('content')
<!-- Portfolio Section -->
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        {{-- <section class="page-section portfolio" id="alurpengajuan"> --}}
        <div class="container">
            <!-- Portfolio Section Heading -->
            <h2 class="page-section-heading text-center text-white mb-0">Alur Pengajuan Magang</h2><!-- Icon Divider -->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>
        </div>
        <div class="divider-custom">
            <div class="divider-custom-icon">
                <p class="masthead-subheading font-weight-light mb-0 text-center text-white">1</p>
                <p class="masthead-subheading font-weight-light mb-0 text-white">Melakukan registrasi di <i>website</i>
                    SiMagang</p>
            </div>
        </div>
        <div class="divider-custom">
            <div class="divider-custom-icon">
                <p class="masthead-subheading font-weight-light mb-0 text-center text-white">2</p>
                <p class="masthead-subheading font-weight-light mb-0 text-white">Membuka fitur Formulir Pengajuan</p>
            </div>
        </div>
        <div class="divider-custom">
            <div class="divider-custom-icon">
                <p class="masthead-subheading font-weight-light mb-0 text-center text-white">3</p>
                <p class="masthead-subheading font-weight-light mb-0 text-white">Mengisi Formulir Pengajuan dan
                    mengunggah file Surat Pengajuan</p>
            </div>
        </div>
        <div class="divider-custom">
            <div class="divider-custom-icon">
                <p class="masthead-subheading font-weight-light mb-0 text-center text-white">4</p>
                <p class="masthead-subheading font-weight-light mb-0 text-white">Menunggu keputusan penerimaan magang
                </p>
            </div>
        </div>
        <div class="divider-custom">
            <div class="divider-custom-icon">
                <p class="masthead-subheading font-weight-light mb-0 text-center text-white">5</p>
                <p class="masthead-subheading font-weight-light mb-0 text-white">Mengisi pendataan jika telah diterima
                    magang</p>
            </div>
        </div>
        {{-- </section> --}}
    </div>
</header>
@endsection

resources/views/user/form_pengajuan.blade.php
@extends('layouts.app')
@extends('user.komponen.bottombar')
@extends('user.komponen.topbar')

@section('content')
@if (session('status'))
{{ session('status') }}
@endif
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header" style="color:black">{{ __('Form Pengajuan') }}</div>

                        <div class="card-body">
                            <form method="POST" action="{{ route('pengajuan.store') }}" enctype="multipart/form-data">
                                @csrf

                                <div class="form-group row">
                                    <label for="nama_pengaju" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Nama Pengaju') }}</label>

                                    <div class="col-md-6">
                                        <input id="nama_pengaju" type="text" class="form-control" name="nama_pengaju"
                                            value="{{auth()->user()->name}}" readonly>

                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="no_induk" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Nomor Induk Pengaju') }}</label>

                                    <div class="col-md-6">
                                        <input id="no_induk" type="text" class="form-control"
                                            name="no_induk" required>

                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="email" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('E-mail') }}</label>

                                    <div class="col-md-6">
                                        <input id="email" type="text" class="form-control" name="email"
                                            value="{{auth()->user()->email}}" readonly>

                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="no_telp" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Nomor Telpon') }}</label>

                                    <div class="col-md-6">
                                        <input id="no_telp" type="number" class="form-control" name="no_telp" required>

                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="instansi_pendidikan" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Instansi Pendidikan') }}</label>

                                    <div class="col-md-6">
                                        <input id="instansi_pendidikan" type="text" class="form-control"
                                            name="instansi_pendidikan" required>

                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="jurusan" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Jurusan') }}</label>

                                    <div class="col-md-6">
                                        <input id="jurusan" type="text" class="form-control"
                                            name="jurusan" required>

                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="mulai_magang" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Mulai Magang') }}</label>

                                        <div class="col-md-6">
                                            <input id="mulai_magang" type="date" class="form-control" name="mulai_magang"
                                                required>

                                        </div>
                                </div>
                                <div class="form-group row">
                                    <label for="selesai_magang" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Selesai Magang') }}</label>

                                        <div class="col-md-6">
                                            <input id="selesai_magang" type="date" class="form-control" name="selesai_magang"
                                                required>

                                        </div>
                                </div>
                                <div class="form-group row">
                                    <label for="nama_anggota1" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Nama Anggota 1') }}</label>

                                    <div class="col-md-6">
                                        <input id="nama_anggota1" type="text" class="form-control" name="nama_anggota1">

                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="no_induk1" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Nomor Induk Anggota 1') }}</label>

                                    <div class="col-md-6">
                                        <input id="no_induk1" type="text" class="form-control"
                                            name="no_induk1">

                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="email1" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('E-mail Anggota 1') }}</label>

                                    <div class="col-md-6">
                                        <input id="email1" type="email" class="form-control"
                                            name="email1">

                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="no_telp1" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Nomor Telpon Anggota 1') }}</label>

                                    <div class="col-md-6">
                                        <input id="no_telp1" type="text" class="form-control"
                                            name="no_telp1">

                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="nama_anggota2" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Nama Anggota 2') }}</label>

                                    <div class="col-md-6">
                                        <input id="nama_anggota2" type="text" class="form-control" name="nama_anggota2">

                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="no_induk2" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Nomor Induk Anggota 2') }}</label>

                                    <div class="col-md-6">
                                        <input id="no_induk2" type="text" class="form-control"
                                            name="no_induk2">

                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="email2" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('E-mail Anggota 2') }}</label>

                                    <div class="col-md-6">
                                        <input id="email2" type="email" class="form-control"
                                            name="email2">

                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="no_telp2" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Nomor Telpon Anggota 2') }}</label>

                                    <div class="col-md-6">
                                        <input id="no_telp2" type="text" class="form-control"
                                            name="no_telp2">

                                    </div>
                                </div>
                                {{--
                                <div class="form-group row">
                                    <label for="jumlah_anggota" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Jumlah Anggota') }}</label>

                                <div class="col-md-6">
                                    <select name="jumlah_anggota" id="jumlah_anggota"
                                        class="form-control form-control-user" required>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                        </div> --}}

                        <div class="form-group row">
                            <label for="file_pengajuan" class="col-md-4 col-form-label text-md-right"
                                style="color:black">{{__('Unggah File (Pdf)')}}</label>
                            <div class="col-md-3 text-md-left">
                                <input type="file" id="file_pengajuan" name="file_pengajuan" style="color:black"
                                    accept="application/pdf" required />
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Ajukan') }}
                                </button>
                            </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</header>

@endsection

resources/views/user/list_logbook_magang.blade.php
@extends('layouts.app')
@extends('user.komponen.bottombar')
@extends('user.komponen.topbar')

@section('content')
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <div class="container-fluid">

            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Logbook Magang</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Tanggal</th>
                                    <th>Lokasi</th>
                                    <th>Keterangan</th>
                                    <th>Status</th>
                                    <th>Ubah</th>
                                    {{-- <th>Hapus</th> --}}
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Tanggal</th>
                                    <th>Lokasi</th>
                                    <th>Keterangan</th>
                                    <th>Status</th>
                                    <th>Ubah</th>
                                    {{-- <th>Hapus</th> --}}
                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach ($logbook as $logbook)
                                <tr>
                                    <td>{{$logbook->tanggal}}</td>
                                    <td>{{$logbook->lokasi}}</td>
                                    <td>{{$logbook->keterangan}}</td>
                                    @if ($logbook->status==1)
                                    <td>Menunggu Verifikasi Pembimbing BKN</td>
                                    @elseif($logbook->status==2)
                                    <td>Diverifikasi</td>
                                    @elseif($logbook->status==0)
                                    <td>Ditolak</td>
                                    @endif
                                    <td>
                                        <form action="{{route('logbook.edit', $logbook->id)}}" method="get">
                                            <button type="submit"
                                                class="btn btn-primary btn-user btn-block">Ubah</button>
                                        </form>
                                    </td>
                                    {{-- @if($perkembangan->status==2)
                                    <td></td>
                                    @else
                                    <td>
                                        <form action="#{{--route('pengajuan.destroy', [$pengajuan['id']])--}}"
                                            {{-- method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-user btn-block">
                                                Hapus
                                            </button>
                                        </form>
                                    </td>
                                    @endif --}}
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <hr>
                    <a href="{{route('logbook.create')}}">
                        <button type="button" class="btn btn-primary btn-user btn-block">
                            Tambah Logbook Magang
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>

@endsection

resources/views/user/list_pengajuan.blade.php
@extends('layouts.app')
@extends('user.komponen.bottombar')
@extends('user.komponen.topbar')

@section('content')
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <div class="container-fluid">

            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Perkembangan Pengajuan</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Nama Pengaju</th>
                                    <th>Instansi Pendidikan</th>
                                    <th>Status</th>
                                    <th>Lihat File</th>
                                    <th>Ubah</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Nama Pengaju</th>
                                    <th>Instansi Pendidikan</th>
                                    <th>Status</th>
                                    <th>Lihat File</th>
                                    <th>Ubah</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach ($pengajuan as $pengajuan)
                                <tr>
                                    <td>{{$pengajuan['nama_pengaju']}}</td>
                                    <td>{{$pengajuan['asal_surat']}}</td>
                                <td>{{$pengajuan->keterangan}}</td>
                                    <td>
                                        <a href="{{route('open_file', [$pengajuan['id']])}}">
                                            <button type="button" class="btn btn-primary btn-user btn-block">
                                                Lihat File
                                            </button>
                                        </a>
                                    </td>
                                    @if($pengajuan['status']==1)
                                    <td>
                                        <a href="{{route('pengajuan.edit', [$pengajuan['id']])}}">
                                            <button type="button" class="btn btn-primary btn-user btn-block">
                                                Ubah
                                            </button>
                                        </a>
                                    </td>
                                    @elseif($pengajuan['status']==0)
                                    <td>
                                        <a href="{{route('error_ditolak')}}">
                                            <button type="button" class="btn btn-primary btn-user btn-block">
                                                Ubah
                                            </button>
                                        </a>
                                    </td>
                                    @elseif($pengajuan['status']==2)
                                    <td>
                                        <a href="{{route('error_pengajuan_diproses')}}">
                                            <button type="button" class="btn btn-primary btn-user btn-block">
                                                Ubah
                                            </button>
                                        </a>
                                    </td>
                                    @else
                                    <td>
                                        <a href="{{route('error_diterima')}}">
                                            <button type="button" class="btn btn-primary btn-user btn-block">
                                                Ubah
                                            </button>
                                        </a>
                                    </td>
                                    @endif
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</header>
@endsection

resources/views/user/tambah_logbook_magang.blade.php
@extends('layouts.app')
@extends('user.komponen.bottombar')
@extends('user.komponen.topbar')

@section('content')
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header" style="color:black">{{ __('Pengisian Logbook Magang') }}</div>

                        <div class="card-body">
                            <form method="POST" action="{{route('logbook.store')}}" enctype="multipart/form-data">
                                @csrf
                                @method('POST')
                                <div class="form-group row">
                                    <label for="tanggal" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Tanggal') }}</label>

                                    <div class="col-md-6">
                                        <input id="tanggal" type="date" class="form-control" name="tanggal"
                                            required>

                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="lokasi" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Lokasi') }}</label>

                                    <div class="col-md-6">
                                        <input id="lokasi" type="text" class="form-control"
                                            name="lokasi" required>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="keterangan" class="col-md-4 col-form-label text-md-right"
                                        style="color:black">{{ __('Keterangan') }}</label>

                                    <div class="col-md-6">
                                        <input id="keterangan" type="text" class="form-control"
                                            name="keterangan" required>
                                    </div>
                                </div>

                                <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            {{ __('Tambah Data') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

@endsection