routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::post('/login/custom', [
    'uses' => 'LoginController@login',
    'as' => 'login.custom'
]);


//Resource
Auth::routes();


//user
Route::group(['middleware' => ['auth' => 'user']], function () {
    Route::resource('pengajuan', 'PengajuanController');
    Route::resource('logbook', 'IsiLogbookController');
    Route::resource('magang', 'MagangController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/error_ditolak', 'MagangController@errorPenolakan')->name('error_ditolak');
    Route::get('/error_pengajuan_diproses', 'PengajuanController@errorDiproses')->name('error_pengajuan_diproses');
    Route::get('/error_pengajuan', 'PengajuanController@sudahPengajuan')->name('error_pengajuan');
    Route::get('/error_belum_magang', 'MagangController@error_belum_diterima_magang')->name('error_status');
    Route::get('/error_sudah_diterima', 'MagangController@error_sudah_diterima_magang')->name('error_diterima');
});

//admin
Route::group(['middleware' => ['auth' => 'admin']], function () {
    Route::resource('penilaian', 'PenilaianController');
    Route::get('/home_dashboard', function () {
        return view('admin/home_admin');
    })->name('admin_dashboard');
    Route::get('/list_pengajuan_admin', 'PengajuanController@index_admin')->name('list_pengajuan_admin');
    Route::get('/edit_pengajuan_admin/{id}', 'PengajuanController@edit_pengajuan_admin')->name('edit_pengajuan_admin');
    Route::post('/update_pengajuan_admin/{id}', 'PengajuanController@update_admin')->name('update_pengajuan_admin');
    Route::post('/tolak_pengajuan/{id}', 'PengajuanController@tolak_admin')->name('tolak_pengajuan');
    Route::post('/terima_pengajuan/{id}', 'PengajuanController@terima_ropeg_admin')->name('terima_pengajuan');
    Route::post('/teruskan_kabiro/{id}', 'PengajuanController@teruskan_kabiro')->name('teruskan_kabiro');
    Route::post('/terima_magang/{id}', 'PengajuanController@terima_magang_kabag')->name('terima_magang');
    Route::get('/list_magang_admin', 'MagangController@index_admin')->name('list_magang_admin');
    Route::get('/list_logbook_admin', 'IsiLogbookController@index_admin')->name('list_logbook_admin');
    Route::post('/acc_logbook_admin/{id}', 'IsiLogbookController@acc_logbook')->name('acc_logbook');
    Route::post('/tolak_logbook_admin/{id}', 'IsiLogbookController@tolak_logbook')->name('tolak_logbook');
    Route::resource('tambahadmin', 'TambahAdminController');

    Route::get('/create_penilaian/{id}', 'PenilaianController@create_admin')->name('tambah_penilaian');
    Route::post('/tambah_penilaian/{id}', 'PenilaianController@store_admin')->name('simpan_penilaian');
    Route::post('/selesaikan_magang/{id}', 'MagangController@selesaikan_magang')->name('selesaikan_magang');
});





// guest
Route::get('/alur_pengajuan', function () {
    return view('/user/alur_pengajuan');
})->name('alur_pengajuan');
Route::get('/tentang_simagang', function () {
    return view('/user/tentang_simagang');
})->name('tentang_simagang');

//lain
Route::get('/file/{id}', 'PengajuanController@openFile')->name('open_file');

resources/views/admin/komponen/sidebar_admin.blade.php
 @section('sidebar_admin')


 <!-- Sidebar -->
 <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

     <!-- Sidebar - Brand -->
     <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{route('admin_dashboard')}}">
         <div class="sidebar-brand-icon">
             <i class="fas fa-user"></i>
         </div>
         <div class="sidebar-brand-text mx-3">SiMagang</div>
     </a>

     <!-- Divider -->
     <hr class="sidebar-divider my-0">

     <!-- Nav Item - Dashboard -->
     <li class="nav-item">
         <a class="nav-link" href="{{route('admin_dashboard')}}">
             <i class="fas fa-fw fa-tachometer-alt"></i>
             <span>Beranda</span></a>
     </li>

     <!-- Divider -->
     <hr class="sidebar-divider">

     <!-- Heading -->
     <div class="sidebar-heading">
         Daftar
     </div>

     <!-- Nav Item - Tables -->
     <li class="nav-item">
         <a class="nav-link" href="{{route('list_pengajuan_admin')}}">
             <i class="fas fa-fw fa-file"></i>
             <span>Pengajuan</span></a>
     </li>
     @if (Auth::user()->id_bagian == null)

     @else
     <!-- Nav Item - Tables -->
     <li class="nav-item">
         <a class="nav-link" href="{{route('list_magang_admin')}}">
             <i class="fas fa-fw fa-users"></i>
             <span>Data Magang</span></a>
     </li>

     <!-- Nav Item - Tables -->
     <li class="nav-item">
         <a class="nav-link" href="{{route('list_logbook_admin')}}">
             <i class="fas fa-fw fa-book"></i>
             <span>Data Logbook</span></a>
     </li>
     @endif
     @if (Auth::user()->id_biro == 1 && Auth::user()->id_bagian == null)
     <li class="nav-item">
        <a class="nav-link" href="{{route('tambahadmin.index')}}">
            <i class="fas fa-fw fa-user"></i>
            <span>Daftar Pengguna</span></a>
    </li>
     @if (Auth::user()->id_biro == null)
     <!-- Nav Item - Pengguna -->

     @endif
     @else

     @endif



     <!-- Sidebar Toggler (Sidebar) -->
     <div class="text-center d-none d-md-inline">
         <button class="rounded-circle border-0" id="sidebarToggle"></button>
     </div>

 </ul>
 <!-- End of Sidebar -->
 @endsection

resources/views/admin/komponen/topbar_admin.blade.php
 @section('topbar_admin')
 <!-- Topbar -->
 <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

     <!-- Sidebar Toggle (Topbar) -->
     <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
         <i class="fa fa-bars"></i>
     </button>
     {{--
    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
      <div class="input-group">
        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search fa-sm"></i>
          </button>
        </div>
      </div>
    </form> --}}

     <!-- Topbar Navbar -->
     <ul class="navbar-nav ml-auto">

         <!-- Nav Item - Search Dropdown (Visible Only XS) -->
         <li class="nav-item dropdown no-arrow d-sm-none">
             <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown"
                 aria-haspopup="true" aria-expanded="false">
                 <i class="fas fa-search fa-fw"></i>
             </a>
             <!-- Dropdown - Messages -->
             <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                 aria-labelledby="searchDropdown">
                 <form class="form-inline mr-auto w-100 navbar-search">
                     <div class="input-group">
                         <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                             aria-label="Search" aria-describedby="basic-addon2">
                         <div class="input-group-append">
                             <button class="btn btn-primary" type="button">
                                 <i class="fas fa-search fa-sm"></i>
                             </button>
                         </div>
                     </div>
                 </form>
             </div>
         </li>


         <div class="topbar-divider d-none d-sm-block"></div>

         <!-- Nav Item - User Information -->
         <li class="nav-item dropdown no-arrow">
             <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                 aria-haspopup="true" aria-expanded="false">
                 <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->name }}</span>
                 <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
             </a>
             <!-- Dropdown - User Information -->
             <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                 <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
          document.getElementById('logout-form').submit();">
                     <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                     Logout
                 </a>
                 <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                     @csrf
                 </form>
             </div>
         </li>

     </ul>

 </nav>
 <!-- End of Topbar -->
 @endsection