routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::post('/login/custom', [
    'uses' => 'LoginController@login',
    'as' => 'login.custom'
]);


//Resource
Auth::routes();


//user
Route::group(['middleware' => ['auth' => 'user']], function () {
    Route::resource('pengajuan', 'PengajuanController');
    Route::resource('logbook', 'IsiLogbookController');
    Route::resource('magang', 'MagangController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/error_ditolak', 'MagangController@errorPenolakan')->name('error_ditolak');
    Route::get('/error_pengajuan_diproses', 'PengajuanController@errorDiproses')->name('error_pengajuan_diproses');
    Route::get('/error_pengajuan', 'PengajuanController@sudahPengajuan')->name('error_pengajuan');
    Route::get('/error_belum_magang', 'MagangController@error_belum_diterima_magang')->name('error_status');
    Route::get('/error_sudah_diterima', 'MagangController@error_sudah_diterima_magang')->name('error_diterima');
});

//admin
Route::group(['middleware' => ['auth' => 'admin']], function () {
    Route::resource('penilaian', 'PenilaianController');
    Route::get('/home_dashboard', function () {
        return view('admin/home_admin');
    })->name('admin_dashboard');
    Route::get('/list_pengajuan_admin', 'PengajuanController@index_admin')->name('list_pengajuan_admin');
    Route::get('/edit_pengajuan_admin/{id}', 'PengajuanController@edit_pengajuan_admin')->name('edit_pengajuan_admin');
    Route::post('/update_pengajuan_admin/{id}', 'PengajuanController@update_admin')->name('update_pengajuan_admin');
    Route::post('/tolak_pengajuan/{id}', 'PengajuanController@tolak_admin')->name('tolak_pengajuan');
    Route::post('/terima_pengajuan/{id}', 'PengajuanController@terima_ropeg_admin')->name('terima_pengajuan');
    Route::post('/teruskan_kabiro/{id}', 'PengajuanController@teruskan_kabiro')->name('teruskan_kabiro');
    Route::post('/terima_magang/{id}', 'PengajuanController@terima_magang_kabag')->name('terima_magang');
    Route::get('/list_magang_admin', 'MagangController@index_admin')->name('list_magang_admin');
    Route::get('/list_logbook_admin', 'IsiLogbookController@index_admin')->name('list_logbook_admin');
    Route::post('/acc_logbook_admin/{id}', 'IsiLogbookController@acc_logbook')->name('acc_logbook');
    Route::post('/tolak_logbook_admin/{id}', 'IsiLogbookController@tolak_logbook')->name('tolak_logbook');
    Route::resource('tambahadmin', 'TambahAdminController');

    Route::get('/create_penilaian/{id}', 'PenilaianController@create_admin')->name('tambah_penilaian');
    Route::post('/tambah_penilaian/{id}', 'PenilaianController@store_admin')->name('simpan_penilaian');
    Route::post('/selesaikan_magang/{id}', 'MagangController@selesaikan_magang')->name('selesaikan_magang');
});





// guest
Route::get('/alur_pengajuan', function () {
    return view('/user/alur_pengajuan');
})->name('alur_pengajuan');
Route::get('/tentang_simagang', function () {
    return view('/user/tentang_simagang');
})->name('tentang_simagang');

//lain
Route::get('/file/{id}', 'PengajuanController@openFile')->name('open_file');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_admin', 'id_biro', 'id_bagian',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function pengguna(){
        return $this->hasMany('App\Pengajuan', 'id_pengguna', 'id');
    }

    // public function pengguna_magang(){
    //     return $this->hasOne('App\Magang', 'id_pengguna', 'id');
    // }

    // public function pengguna_logbook()
    // {
    //     return $this->hasMany('App\Logbook', 'id_pengguna', 'id');
    // }

    public function pengguna_biro()
    {
        return $this->belongsTo('App\Biro', 'id_biro', 'id');
    }

    public function pengguna_bagian(){
        return $this->belongsTo('App\Bagian', 'id_bagian', 'id');
    }

    public function is_admin(){
        if($this->is_admin){
            return true;
        }
        else{
            return false;

        }
    }
}

resources/views/user/komponen/bottombar.blade.php
@section('bottombar')
<!-- Footer -->
<footer class="footer text-center">
    <div class="container">
        <div class="row">

            <!-- Footer Location -->
            <div class="col-lg-6 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Lokasi</h4>
                <p class="lead mb-0">Jl. Mayjen Sutoyo No. 12
                    <br>Jakarta Timur 13640
                    <br> Telp 021-8093008</p>
            </div>

            <!-- Footer Social Icons -->
            <div class="col-lg-6 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Media Sosial</h4>
                <a class="btn btn-outline-light btn-social mx-1" href="https://www.facebook.com/BKNgoid/">
                    <i class="fab fa-fw fa-facebook-f"></i>
                </a>
                <a class="btn btn-outline-light btn-social mx-1" href="https://twitter.com/BKNgoid?s=09">
                    <i class="fab fa-fw fa-twitter"></i>
                </a>
                <a class="btn btn-outline-light btn-social mx-1" href="https://www.bkn.go.id">
                    <i class="fab fa-fw fa-dribbble"></i>
                </a>
            </div>



        </div>
    </div>
</footer>
@endsection

resources/views/user/komponen/topbar.blade.php
@section('topbar')


<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{{route('home')}}">SiMagang</a> <button
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"
            class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded"
            data-target="#navbarResponsive" data-toggle="collapse" type="button">Menu <i
                class="fas fa-bars"></i></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li style="list-style: none">
                </li>
                <li class="nav-item mx-0 mx-lg-1">
                    <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
                        href="{{route('alur_pengajuan')}}">Alur Pengajuan</a>
                </li>
                <li class="nav-item mx-0 mx-lg-1">
                    <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
                        href="{{route('tentang_simagang')}}">Tentang SiMagang</a>
                </li>
                @guest
                <li class="nav-item mx-0 mx-lg-1">
                    <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
                        href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
                <li style="list-style: none">@if (Route::has('register'))</li>
                <li class="nav-item mx-0 mx-lg-1">
                    <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
                        href="{{ route('register') }}">{{ __('Registrasi') }}</a>
                </li>
                @endif
                @else

                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link py-3 px-0 px-lg-3 dropdown-toggle" href="#" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a href="{{route('pengajuan.create')}}" class="dropdown-item">{{__('Formulir Pengajuan')}}</a>
                        <a href="{{route('pengajuan.index')}}" class="dropdown-item">{{__('Lihat Pengajuan')}}</a>
                        <a href="{{route('magang.index')}}" class="dropdown-item">{{__('Data Magang')}}</a>
                        <a href="{{route('logbook.index')}}" class="dropdown-item">{{__('Logbook Magang')}}</a>
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>


                    </div>
                </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

@endsection